# Application Config
spring.application.name=bajaj-finserv-api
server.port=${PORT:8080}

# User Configuration (used to build user_id dynamically)
app.user.full-name=Bhavya Gupta
app.user.dob=04032005
app.user.email=bhavyagupta230794@acropolis.in
app.user.roll-number=0827CS231062

# Logging
logging.level.com.bajaj=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
